my_bank_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "user#index"
  get 'home_page', to: 'user#home'
  get 'open_account', to: 'user#open_account'
  get 'deposit_form', to: 'account#deposit_form'
  get 'withdraw_form', to: 'account#withdraw_form'
  get 'transfer_form', to: 'account#transfer_form'
  get 'transactions', to: 'account#transaction'
  post 'deposit', to: 'account#deposit'
  post 'withdraw', to: 'account#withdraw'
  post 'transfer', to: 'account#transfer'
end

my_bank_app/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

my_bank_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_bank_app/app/models/transaction.rb
class Transaction < ApplicationRecord
end

my_bank_app/app/models/user.rb
class User < ApplicationRecord
  has_one :account
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

my_bank_app/app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :find_my_account
  def deposit_form; end

  def transfer_form; end
  
  def withdraw_form; end
  
  def statement; end

  def deposit
    @my_account.balance = @my_account.balance + params[:deposit][:amount].to_f
    @transaction = Transaction.new(deposit_params)
    @transaction.transaction_type = 'deposit'
    @transaction.account_to = @my_account.account_no
    if @my_account.save
      if @transaction.save
        flash.now[:alert] = 'Money Deposited'
        redirect_to home_page_path
      else
        flash.now[:alert] = 'Something went wrong!'
        @my_account.balance = @my_account.balance -  params[:deposit][:amount].to_f
        @my_account.update
        redirect_to home_page_path
      end
    else
      flash.now[:alert] = 'Something went wrong!'
      redirect_to home_page_path
    end
  end

  def withdraw
    if @my_account.balance > params[:withdraw][:amount].to_f
      @my_account.balance = @my_account.balance - params[:withdraw][:amount].to_f
      if @my_account.save
        @transaction = Transaction.new(withdraw_params)
        @transaction.transaction_type = 'withdraw'
        @transaction.account_from = @my_account.account_no
        if @transaction.save
          flash.now[:alert] = 'Money Withdrawed'
          redirect_to home_page_path
        else
          flash.now[:alert] = 'Something went wrong!'
          @my_account.balance = @my_account.balance + params[:withdraw][:amount].to_f
          @my_account.update
          redirect_to home_page_path
        end
      else
        flash.now[:alert] = 'Something went wrong!'
        redirect_to home_page_path
      end
    else
      flash.now[:alert] = 'You dont have enough balance!'
      redirect_to home_page_path
    end  
  end

  def transfer
    @transfer_to = Account.find_by(account_no: params[:transfer][:account_to])
    if @transfer_to == nil
      flash.now[:alert] = 'Account not Found You want to transfer to!'
      redirect_to transfer_form_path
    else
      if @my_account.balance > params[:transfer][:amount].to_f
        @my_account.balance = @my_account.balance - params[:transfer][:amount].to_f
        @transfer_to.balance = @transfer_to.balance + params[:transfer][:amount].to_f
        if @my_account.save && @transfer_to.save
          @transaction = Transaction.new(transfer_params)
          @transaction.transaction_type = 'transfer'
          @transaction.account_from = @my_account.account_no
          @transaction.account_to = params[:transfer][:account_to]
          @transaction.save
          flash.now[:alert] = 'Transfer done'
          redirect_to home_page_path
        else
          flash.now[:alert] = 'Something went wrong!'
          redirect_to home_page_path
        end
      else
        flash.now[:alert] = 'You dont have enough balance to transfer!'
        redirect_to home_page_path
      end
    end
  end

  def transaction
    @transactions = Transaction.where(account_to: @my_account.account_no).or(Transaction.where(account_from: @my_account.account_no))
  end

  private
  def find_my_account
    @my_account = Account.find_by(user_id: current_user.id)
  end

  def deposit_params
    params.require(:deposit).permit(:amount)
  end

  def withdraw_params
    params.require(:withdraw).permit(:amount)
  end

  def transfer_params
    params.require(:transfer).permit(:amount, :transfer_to)
  end
end

my_bank_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    home_page_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name contact_no])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name contact_no])
  end
  
end

my_bank_app/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  
  def home 
    @my_account = Account.find_by(user_id: current_user.id)
  end

  def open_account
    @account = Account.new()
    @account.user_id = current_user.id
    @account.account_no = current_user.contact_no.to_s
    if @account.save
      flash.now[:alert] = 'Congratulations! Account Opened'
      redirect_to home_page_path
    else
      flash.now[:alert] = 'Something went wrong!'
      redirect_to home_page_path
    end
  end
  
end

my_bank_app/app/helpers/account_helper.rb
module AccountHelper
end

my_bank_app/app/helpers/application_helper.rb
module ApplicationHelper
end

my_bank_app/app/helpers/user_helper.rb
module UserHelper
end

my_bank_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBankApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

my_bank_app/app/views/user/home.html.erb
<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
<h4>Welcome to My Bank-App</h4>
<% if @my_account == nil %>
  <%= link_to 'Open an Account', open_account_path %>
<% else %>
  <table border="1">
    <tr>
      <th>Account Number</th>
      <th>Balance</th>
      <th>Deposit</th>
      <th>Withdraw</th>
      <th>Transfer</th>
      <th>Statements</th>
    </tr>
    <tr>
      <td>
        <%= @my_account.account_no %>
      </td>
      <td>
        <%= @my_account.balance %>
      </td>
      <td>
        <%= link_to 'Deposit', deposit_form_path %>
      </td> 
      <td>
        <%= link_to 'Withdraw', withdraw_form_path %>
      </td>
      <td>
        <%= link_to 'Transfer', transfer_form_path %>
      </td>
      <td>
        <%= link_to 'Statements', transactions_path %>
      </td> 
    </tr>
  </table>
<% end %>

my_bank_app/app/views/user/index.html.erb
<%= link_to 'Sign In', new_user_session_path %>
<%= link_to 'Sign Up', new_user_registration_path %>